version: '3'

services:
  db:
    container_name: poli-link-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: polilink_database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./poli-link-db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  api:
    container_name: poli-link-api
    build: ./poli-link-api
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./poli-link-api/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    container_name: poli-link-web
    build: ./poli-link-web
    ports:
      - 3000:3000
    volumes:
      - ./poli-link-web:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    command: sh -c "cd poli-link/ && yarn dev"