version: '3'

services:
  api:
    container_name: poli-link-api
    build: ./
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/code
    network_mode: bridge
    restart: always
    tty: true
    stdin_open: true
    environment:
      PROFILE: "minimal"
      VIRTUAL_HOST: api.jq-collection.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: api.jq-collection.com
      LETSENCRYPT_EMAIL: konnokiyotaka@jq-collection.com