# Generated by Django 2.2.12 on 2021-04-29 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('name_e', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
