# Generated by Django 2.2.12 on 2021-04-30 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0002_ministry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polilink_api.Ministry')),
            ],
        ),
    ]
