# Generated by Django 2.2.12 on 2021-04-30 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0003_council'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('name_kana', models.CharField(max_length=64)),
                ('name_e', models.CharField(blank=True, max_length=64, null=True)),
                ('url_official', models.CharField(blank=True, max_length=256, null=True)),
                ('url_wikipedia', models.CharField(blank=True, max_length=256, null=True)),
                ('url_twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('url_facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('url_youtube', models.CharField(blank=True, max_length=256, null=True)),
                ('career_summary', models.TextField()),
            ],
        ),
    ]
