# Generated by Django 2.2.12 on 2021-05-02 00:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=256, null=True)),
                ('position', models.CharField(max_length=256, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polilink_api.Council')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polilink_api.Person')),
            ],
        ),
    ]
