# Generated by Django 2.2.12 on 2021-05-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0005_councilmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polilink_api.Person'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
