# Generated by Django 2.2.12 on 2021-05-02 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0006_auto_20210502_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMeeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField()),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polilink_api.Council')),
            ],
        ),
    ]
