# Generated by Django 2.2.12 on 2021-05-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0007_councilmeeeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouncilMeeeting',
            new_name='CouncilMeeting',
        ),
    ]
