# Generated by Django 2.2.12 on 2021-05-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0009_meetingspeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmeeting',
            name='url_document',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='councilmeeting',
            name='url_minute',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='meetingspeech',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingspeech',
            name='speech',
            field=models.TextField(blank=True, null=True),
        ),
    ]
