# Generated by Django 3.2 on 2021-05-30 00:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0010_auto_20210504_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='career_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CouncilTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('order', models.IntegerField()),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council', to='polilink_api.council')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_council', to='polilink_api.council')),
            ],
        ),
    ]
