# Generated by Django 3.2 on 2021-05-30 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0011_auto_20210530_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counciltree',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council', to='polilink_api.council'),
        ),
    ]
