# Generated by Django 3.2 on 2021-05-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0012_alter_counciltree_council'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counciltree',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council', to='polilink_api.council'),
        ),
        migrations.AlterField(
            model_name='counciltree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_council', to='polilink_api.council'),
        ),
    ]
