# Generated by Django 3.2.6 on 2022-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0014_councilnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilnews',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='councilnews',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='councilnews',
            name='site_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='councilnews',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='councilnews',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='polilink_api.council'),
        ),
    ]
