# Generated by Django 3.2.6 on 2022-04-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0015_auto_20220125_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilnews',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polilink_api.council'),
        ),
    ]
