# Generated by Django 3.2.6 on 2022-04-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polilink_api', '0016_alter_councilnews_council'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilnews',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='polilink_api.council'),
        ),
    ]
