name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  # build:

  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.7, 3.8, 3.9]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Deploy
  #     env:
  #       SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #       SSH_USER: ${{ secrets.SSH_USER }}
  #       SSH_ADDR: ${{ secrets.SSH_ADDR }}
  #       SSH_PORT: ${{ secrets.SSH_PORT }}
  #       SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
  #     run: |
  #       echo "$SECRET_KEY" > secret_key
  #       chmod 600 secret_key
  #       ssh -oStrictHostKeyChecking=no ${SSH_USER}@${SSH_ADDR} -i secret_key -p ${SSH_PORT} "$SSH_COMMAND"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SK }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            sudo sh /home/poli-link/poli-link-api/deploy.sh  